#Comment to trigger new pull request
#merge when ready
#Switched on Only Build Pull requests feature for this project
#Comment to trigger commit on Server
common:
  godel-cache:
    key: &godel-cache-key v1-godel-cache-{{ checksum "godelw" }}-{{ checksum "godel/config/godel.yml" }}
    <<: &restore-godel-cache
      restore_cache:
        keys:
          - *godel-cache-key
    <<: &save-godel-cache
      save_cache:
        key: *godel-cache-key
        paths:
          - ~/.godel

  test-results:
    dir: &results-dir /tmp/test-results
    <<: &store-results
      store_test_results:
        path: *results-dir
    <<: &store-artifacts
      store_artifacts:
        path: *results-dir
        destination: test-results

### Jobs ###

version: 2
jobs:
  build:
    working_directory: /go/src/github.com/palantir/bulldozer
    docker:
      - image: circleci/golang:1.13.4-stretch
    steps:
      - checkout
      - *restore-godel-cache
      - run: ./godelw version
      - *save-godel-cache
      - run: ./godelw build
      - persist_to_workspace:
          root: .
          paths:
            - build/bulldozer

  automated-tests:
    working_directory: /go/src/github.com/palantir/bulldozer
    environment:
       TESTS_DIR: *results-dir
    docker:
      - image: circleci/golang:1.13.4-stretch
    steps:
      - checkout
      - *restore-godel-cache
      - run: ./godelw version
      - *save-godel-cache
      - run: mkdir -p "${TESTS_DIR}"
      - run: ./godelw verify --apply=false --junit-output="$TESTS_DIR/$CIRCLE_PROJECT_REPONAME-tests.xml"
      - *store-results
      - *store-artifacts

  list-critical-changes:
    working_directory: /go/src/github.com/palantir/bulldozer
    docker:
      - image: circleci/golang:1.13.4-stretch
    steps:
      - checkout
      - run: echo "This job is listing all the critical changes introduced by the code"

### Workflows ###

workflows:
  version: 2
  build:
    jobs:
      - dev-sign-off: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
      - list-critical-changes:
          filters: { tags: { only: /.*/ } }
          requires:
           - dev-sign-off
      - build:
          filters: { tags: { only: /.*/ } }
          requires:
           - dev-sign-off
           - list-critical-changes
      - automated-tests:
          filters: { tags: { only: /.*/ } }
          requires:
           - build
      - qa-sign-off: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - automated-tests
      - block-if-long-maintainer-and-next-window-is-not-saturday: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - qa-sign-off
