#Comment to trigger new commit
#merge when ready
common:
  godel-cache:
    key: &godel-cache-key v1-godel-cache-{{ checksum "godelw" }}-{{ checksum "godel/config/godel.yml" }}
    <<: &restore-godel-cache
      restore_cache:
        keys:
          - *godel-cache-key
    <<: &save-godel-cache
      save_cache:
        key: *godel-cache-key
        paths:
          - ~/.godel

  test-results:
    dir: &results-dir /tmp/test-results
    <<: &store-results
      store_test_results:
        path: *results-dir
    <<: &store-artifacts
      store_artifacts:
        path: *results-dir
        destination: test-results

### Jobs ###

version: 2
jobs:
  build:
    working_directory: /go/src/github.com/palantir/bulldozer
    docker:
      - image: circleci/golang:1.13.4-stretch
    steps:
      - checkout
      - *restore-godel-cache
      - run: ./godelw version
      - *save-godel-cache
      - run: ./godelw build
      - persist_to_workspace:
          root: .
          paths:
            - build/bulldozer

  mab-tests:
    working_directory: /go/src/github.com/palantir/bulldozer
    environment:
       TESTS_DIR: *results-dir
    docker:
      - image: circleci/golang:1.13.4-stretch
    steps:
      - checkout
      - *restore-godel-cache
      - run: ./godelw version
      - *save-godel-cache
      - run: mkdir -p "${TESTS_DIR}"
      - run: ./godelw verify --apply=false --junit-output="$TESTS_DIR/$CIRCLE_PROJECT_REPONAME-tests.xml"
      - *store-results
      - *store-artifacts

  testilda:
    working_directory: /go/src/github.com/palantir/bulldozer
    docker:
      - image: circleci/golang:1.13.4-stretch
    steps:
      - checkout
      - run: echo "This is the testilda job"

  deploy-prod-or-clone:
    working_directory: /go/src/github.com/palantir/bulldozer
    docker:
      - image: circleci/golang:1.13.4-stretch
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - *restore-godel-cache
      - run: ./godelw docker build --verbose
      - deploy:
          name: Publish
          command: |
            if [[ "${CIRCLE_BRANCH}" == "develop" ]]; then
              docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
              docker push brianoh1979/bulldozer:snapshot
            fi
            if [[ -n "${CIRCLE_TAG}" ]] ; then
              docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
              docker push brianoh1979/bulldozer:latest
            fi

### Workflows ###

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters: { tags: { only: /.*/ } }
      - mab-tests-approval: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - build
      - mab-tests:
          filters: { tags: { only: /.*/ } }
          requires:
           - mab-tests-approval
      - testilda-approval: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - mab-tests
      - testilda:
          filters: { tags: { only: /.*/ } }
          requires:
           - testilda-approval
      - deploy-prod-or-clone-approval: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - testilda
      - deploy-prod-or-clone:
          filters: { tags: { only: /.*/ } }
          requires:
            - build
