#Comment to trigger new pull request
#merge when ready
 common:
   godel-cache:
     key: &godel-cache-key v1-godel-cache-{{ checksum "godelw" }}-{{ checksum "godel/config/godel.yml" }}
     <<: &restore-godel-cache
       restore_cache:
         keys:
           - *godel-cache-key
     <<: &save-godel-cache
       save_cache:
         key: *godel-cache-key
         paths:
           - ~/.godel

   test-results:
     dir: &results-dir /tmp/test-results
     <<: &store-results
       store_test_results:
         path: *results-dir
     <<: &store-artifacts
       store_artifacts:
         path: *results-dir
         destination: test-results

# version: 2
 jobs:
   create-deployment:
     executor: aws-eks/python3
     parameters:
       cluster-name:
         description: |
           Name of the EKS cluster
         type: string
     steps:
       - checkout
       - aws-eks/update-kubeconfig-with-authenticator:
           cluster-name: << parameters.cluster-name >>
           install-kubectl: true
       - kubernetes/create-or-update-resource:
           get-rollout-status: true
           resource-file-path: tests/nginx-deployment/deployment.yaml
           resource-name: deployment/nginx-deployment

   test-cluster:
     executor: aws-eks/python3
     parameters:
       cluster-name:
         description: |
           Name of the EKS cluster
         type: string
     steps:
       - kubernetes/install
       - aws-eks/update-kubeconfig-with-authenticator:
           cluster-name: << parameters.cluster-name >>
       - run:
           command: |
             kubectl get services
           name: Test cluster

   build:
     working_directory: /go/src/github.com/palantir/bulldozer
     docker:
       - image: circleci/golang:1.13.4-stretch
     steps:
       - checkout
       - echo $AWS_AREA
       - *restore-godel-cache
       - run: ./godelw version
       - *save-godel-cache
       - run: ./godelw build
       - persist_to_workspace:
           root: .
           paths:
             - build/bulldozer

   automated-tests:
     working_directory: /go/src/github.com/palantir/bulldozer
     environment:
        TESTS_DIR: *results-dir
     docker:
       - image: circleci/golang:1.13.4-stretch
     steps:
       - checkout
       - *restore-godel-cache
       - run: ./godelw version
       - *save-godel-cache
       - run: mkdir -p "${TESTS_DIR}"
       - run: ./godelw verify --apply=false --junit-output="$TESTS_DIR/$CIRCLE_PROJECT_REPONAME-tests.xml"
       - *store-results
       - *store-artifacts

   check-downtime:
     docker:
       - image: circleci/golang:1.13.4-stretch
     steps:
       - checkout
       - run: echo "Verifying that downtime is within the next windows limits"

   prepare-ffcommit:
     docker:
       - image: circleci/golang:1.13.4-stretch
     steps:
       - checkout
       - run: echo "Preparing Fast Forward Commit"

   create-deploy-branch:
     docker:
       - image: circleci/golang:1.13.4-stretch
     steps:
       - checkout
       - run:
          name: Create deployment branch with today's date
          command: |
            dt=$(date +%F)
            dp=deploy-$dt
            git branch $dp
            currenttime=$(date +%H:%M)
            echo $currenttime
            if [[ "$currenttime" != "06:00" ]];  
            then 
              git branch production
              git checkout production
              git merge $dp
              git push -u origin production:production
              bash test-deployment.sh
            else
              echo "Now is not the time to deploy"
            fi

   test-code-on-K8S:
     docker:
       - image: circleci/golang:1.13.4-stretch
     steps:
       - checkout
       - run:
          name: Test the deployment Kubernetes cluster for broken code
          command: |
            bash test-for-broken-code.sh

   deployment-description-alert:
     docker:
       - image: circleci/golang:1.13.4-stretch
     steps:
       - checkout
       - slack/notify:
           channel: CQ4NHT0DC
           color: '#42e2f4'
           message: $CIRCLE_USERNAME is deploying revision $CIRCLE_SHA1 to Production
           webhook: '${SLACK_WEBHOOK}'

 orbs:
   aws-eks: circleci/aws-eks@1.0.0
   kubernetes: circleci/kubernetes@0.11.1
   slack: circleci/slack@3.4.1
 version: 2.1

 workflows:
   build:  
     jobs:
       - check-downtime:
           filters: { tags: { only: /.*/ } }
       - prepare-ffcommit:
           filters: { tags: { only: /.*/ } }
           requires:
            - check-downtime
       - build:
           context:
             - Brian-Context
           filters: { tags: { only: /.*/ } }
           requires:
            - prepare-ffcommit
       - automated-tests:
           filters: { tags: { only: /.*/ } }
           requires:
            - build
       - deployment-description-alert:
           filters: { tags: { only: /.*/ } }
           requires:
            - automated-tests
       - aws-eks/create-cluster:
           aws-region: eu-west-1
           cluster-name: prod-clone2
           requires:
             - automated-tests
       - create-deployment:
           cluster-name: prod-clone2
           requires:
             - aws-eks/create-cluster
       - test-cluster:
           cluster-name: prod-clone2
           requires:
             - create-deployment
       - test-code-on-K8S:
           filters: { tags: { only: /.*/ } }
           requires:
            - test-cluster
       - aws-eks/delete-cluster:
           cluster-name: prod-clone2
           requires:
             - test-code-on-K8S
       - create-deploy-branch:
           filters: { tags: { only: /.*/ } }
           requires:
            - aws-eks/delete-cluster
            - test-code-on-K8S

