product-defaults:
  publish:
    group-id: com.palantir.bulldozer

products:
  bulldozer:
    build:
      output-dir: build
      main-pkg: .
      version-var: github.com/palantir/bulldozer/version.version
      environment:
        CGO_ENABLED: "0"
      os-archs:
      - os: linux
        arch: amd64
    dist:
      output-dir: build
      disters:
        bin:
          type: bin
    docker:
      docker-builders:
        bulldozer:
          type: default
          context-dir: build/docker
          dockerfile-path: Dockerfile
          input-products-dir: .
          script: |
            #!/usr/bin/env bash
            cp -R docker/* ${CONTEXT_DIR}
            cp -R config ${CONTEXT_DIR}
          tag-templates:
            version: "{{Repository}}brianoh1979/bulldozer:{{Version}}"
            latest: "{{Repository}}brianoh1979/bulldozer:latest"
            snapshot: "{{Repository}}brianoh1979/bulldozer:snapshot"
    publish:
      group-id: com.palantir.bulldozer
